/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as ApiUnsubscribeRouteImport } from './routes/api/unsubscribe'
import { Route as LocaleUnsubscribeRouteImport } from './routes/$locale/unsubscribe'
import { Route as ApiJobsCheckUsageRouteImport } from './routes/api/jobs/check-usage'

const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const ApiUnsubscribeRoute = ApiUnsubscribeRouteImport.update({
  id: '/api/unsubscribe',
  path: '/api/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleUnsubscribeRoute = LocaleUnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const ApiJobsCheckUsageRoute = ApiJobsCheckUsageRouteImport.update({
  id: '/api/jobs/check-usage',
  path: '/api/jobs/check-usage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/unsubscribe': typeof LocaleUnsubscribeRoute
  '/api/unsubscribe': typeof ApiUnsubscribeRoute
  '/$locale/': typeof LocaleIndexRoute
  '/api/jobs/check-usage': typeof ApiJobsCheckUsageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/unsubscribe': typeof LocaleUnsubscribeRoute
  '/api/unsubscribe': typeof ApiUnsubscribeRoute
  '/$locale': typeof LocaleIndexRoute
  '/api/jobs/check-usage': typeof ApiJobsCheckUsageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/unsubscribe': typeof LocaleUnsubscribeRoute
  '/api/unsubscribe': typeof ApiUnsubscribeRoute
  '/$locale/': typeof LocaleIndexRoute
  '/api/jobs/check-usage': typeof ApiJobsCheckUsageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/unsubscribe'
    | '/api/unsubscribe'
    | '/$locale/'
    | '/api/jobs/check-usage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/unsubscribe'
    | '/api/unsubscribe'
    | '/$locale'
    | '/api/jobs/check-usage'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/unsubscribe'
    | '/api/unsubscribe'
    | '/$locale/'
    | '/api/jobs/check-usage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
  ApiUnsubscribeRoute: typeof ApiUnsubscribeRoute
  ApiJobsCheckUsageRoute: typeof ApiJobsCheckUsageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/api/unsubscribe': {
      id: '/api/unsubscribe'
      path: '/api/unsubscribe'
      fullPath: '/api/unsubscribe'
      preLoaderRoute: typeof ApiUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/unsubscribe': {
      id: '/$locale/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/$locale/unsubscribe'
      preLoaderRoute: typeof LocaleUnsubscribeRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/api/jobs/check-usage': {
      id: '/api/jobs/check-usage'
      path: '/api/jobs/check-usage'
      fullPath: '/api/jobs/check-usage'
      preLoaderRoute: typeof ApiJobsCheckUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LocaleRouteRouteChildren {
  LocaleUnsubscribeRoute: typeof LocaleUnsubscribeRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleUnsubscribeRoute: LocaleUnsubscribeRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
  ApiUnsubscribeRoute: ApiUnsubscribeRoute,
  ApiJobsCheckUsageRoute: ApiJobsCheckUsageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
